application: stocksearchback
version: 1
runtime: php55
api_version: 1

handlers:
- url: /stocksearchfront.html
  script: stocksearchfront.html
- url: /stocksearchfront.js
  script: stocksearchfront.js
- url: /historical.php
  script: historical.php
- url: /.*
  script: index.php
